name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check for required files
        run: |
          if [ ! -f "src/app/root.tsx" ]; then
            echo "src/app/root.tsx is missing!"
            exit 1
          fi
          if [ ! -f "src/app/routes/_index.tsx" ]; then
            echo "src/app/routes/_index.tsx is missing!"
            exit 1
          fi

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build
        run: npm run build --if-present
